-- Role: testuser
-- DROP ROLE IF EXISTS testuser;

CREATE ROLE testuser WITH
  LOGIN
  NOSUPERUSER
  INHERIT
  CREATEDB
  NOCREATEROLE
  NOREPLICATION
  NOBYPASSRLS
  ENCRYPTED PASSWORD 'SCRAM-SHA-256$4096:dZvrnlOpZu00jyDp5UCaTA==$GnowUMT9aZUnPZa5dDjBJV24oGIbdbE26sFE8GnHL48=:+pW2RpnEC44doWz1YcI5qx9WiYM9L37ZWcLSZntFuCg=';

GRANT postgres TO testuser WITH ADMIN OPTION;
